---
- name: Check ansible version
  import_playbook: ansible_version.yml

- hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: "Set up proxy environment"
      set_fact:
        proxy_env:
          http_proxy: "{{ http_proxy | default ('') }}"
          HTTP_PROXY: "{{ http_proxy | default ('') }}"
          https_proxy: "{{ https_proxy | default ('') }}"
          HTTPS_PROXY: "{{ https_proxy | default ('') }}"
          no_proxy: "{{ no_proxy | default ('') }}"
          NO_PROXY: "{{ no_proxy | default ('') }}"
      no_log: true

- hosts: vagrantbox-1
  gather_facts: true
  roles:
    - { role: ansible-role-git }
    - { role: ansible-role-gcloud }
    - { role: ansible-role-terraform }
    - { role: ansible-role-python3 }
    - { role: ansible-role-ansible }
    - { role: ansible-jq }
    - { role: ansible-role-docker }
    - { role: ansible-role-helm }
    - { role: ansible-yq }
    - { role: ansible-go }
    - { role: ansible-role-make }
    - { role: ansible-apache }